sudo: true
language: node_js
node_js:
  - "8"

branches:
  only:
    - /.*/

install:
  - /usr/bin/yarn install --production=false
  # - npm run test

script:
  - npm run flow
  - npm run jsdoc
  - npm run build

after_success:
  - bash build/deploy.sh "capsula/account-service"

notifications:
  email:
    on_failure: always
