sudo: true
language: node_js
node_js:
  - "8"

branches:
  only:
    - /.*/

install:
  - yarn install --production=false
  - yarn test
  - yarn flow

script:
  - yarn jsdoc
  - yarn build

notifications:
  email:
    on_failure: always
